services:
  python_app:
    image: python_app:latest  # Указываем имя и тег образа
    build:
      context: .
    depends_on:
      - php_app
    restart: always
  php_app:
    image: php_app:latest  # Указываем имя и тег образа
    build:
      context: ./php_app
    ports:
      - "8080:80"
    restart: always