services:
  python_app: # Сервис для Python
    image: python:3.12  # Указываем имя и тег образа
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Подключаем директорию с Python кодом
    command: python /app/main.py  # Команда для запуска Python
    depends_on:
      - php_app  # Указываем, что Python зависит от PHP (запустится после PHP)

  php_app: # Сервис для PHP
    image: php:8.0-apache  # Базовый образ PHP с Apache
    volumes:
      - ./php_app:/var/www/html  # Подключаем директорию с PHP кодом
    ports:
      - "8080:80"  # Пробрасываем порт 8080 (внешний) на 80 (контейнерный)