services:
  python_app: # Сервис для Python
    image: python_app:latest  # Указываем имя и тег образа
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Подключаем директорию с Python кодом